server:
  port: 8079
  login: pgBalancer
  pass: 123789
  timeout: 3
  MaxConns: 20
  MinConns: 5
  MaxConnLifetime: 1
  MaxConnIdleTime: 30
  HealthCheckPeriod: 1
databases:
  - url: jdbc:postgresql://localhost:5432/postgres
    login: postgres
    pass: 123789
    priority: 1
  - url: jdbc:postgresql://localhost:5432/pg2
    login: postgres
    pass: 123789
    priority: 2
  - url: jdbc:postgresql://localhost:5432/pg3
    login: postgres
    pass: 123789
    priority: 3